#!/usr/bin/python3
"""
Module that factorise as many numbrs as possible
into a product of two smaller numbers
"""
import sys


def factorise(number):
    """
    Function that print the factorisation result
    Args:
        -number (int): number to be factorise
    """
    for p in range(2, number):
        if number % p == 0:
            q = number // p
            print("{}={}*{}".format(number, p, q))
            return


if len(sys.argv) != 2:
    print("Usage: python factors.py <file>")
    sys.exit(1)

try:
    with open(sys.argv[1], 'r') as file:
        for line in file:
            number = int(line.strip())
            if number <= 1:
                print("Invalid input: {} should be > 1".format(number))
            else:
                factorise(number)
        sys.exit(0)
except FileNotFoundError:
    print("Error: File {} not found".format(sys.argv[1]))
    sys.exit(1)
except ValueError:
    print("Error: Invalid input in the file")
    sys.exit(1)
